<?php

namespace AppBundle\Repository;

/**
 * TradRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradRepository extends \Doctrine\ORM\EntityRepository
{
}
