<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgu7ymu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgu7ymu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPgu7ymu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPgu7ymu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPgu7ymu\appProdProjectContainer(array(
    'container.build_hash' => 'Pgu7ymu',
    'container.build_id' => 'c673bd7b',
    'container.build_time' => 1518598908,
));
