<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0vtxkyj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0vtxkyj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0vtxkyj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0vtxkyj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0vtxkyj\appDevDebugProjectContainer(array(
    'container.build_hash' => '0vtxkyj',
    'container.build_id' => 'a8ed72d5',
    'container.build_time' => 1518604365,
));
